# Generated by Django 2.2 on 2020-11-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0002_auto_20201104_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
