# Generated by Django 2.2 on 2020-11-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0003_auto_20201105_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('proveedor', models.ManyToManyField(to='Pedidos.Proveedor')),
            ],
        ),
    ]
