# Generated by Django 2.2 on 2020-11-13 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0004_cerveza'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cerveza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Cerveza')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cerveza', models.ManyToManyField(through='Pedidos.LineaPedido', to='Pedidos.Cerveza')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Pedido'),
        ),
    ]
