# Generated by Django 2.2 on 2020-11-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0006_auto_20201125_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='lineaPedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='LineaPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
