# Generated by Django 2.2 on 2020-11-26 13:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pedidos', '0007_auto_20201125_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cerveza', models.ManyToManyField(through='Pedidos.LineaPedido', to='Pedidos.Cerveza')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pedidos.Proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='Pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Pedido'),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='cerveza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Cerveza'),
        ),
    ]
