# Generated by Django 2.2 on 2021-08-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0008_auto_20201126_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='Pedido',
            new_name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fechaEntrega',
            field=models.DateField(auto_now=True),
        ),
    ]
