# Generated by Django 2.2 on 2021-08-26 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0009_auto_20210826_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cerveza',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='LineaPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
