# Generated by Django 2.2 on 2021-08-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0012_auto_20210827_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fechaEntrega',
            field=models.DateField(auto_now=True),
        ),
    ]
