# Generated by Django 2.2 on 2021-08-27 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0013_pedido_fechaentrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='fechaEntrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
