# Generated by Django 2.2 on 2021-08-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0014_auto_20210827_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fechaEntrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
