# Generated by Django 2.2 on 2021-08-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0015_pedido_fechaentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='entregado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='pendiete',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
