# Generated by Django 2.2 on 2021-08-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0016_auto_20210828_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='entregado',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='pendiete',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
