# Generated by Django 2.2 on 2021-08-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0017_auto_20210828_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pendiete',
            new_name='pendiente',
        ),
    ]
