# Generated by Django 2.2 on 2021-09-09 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0018_auto_20210828_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroRemito', models.PositiveIntegerField()),
                ('fechaIngreso', models.DateField(auto_now=True)),
                ('fechaRemito', models.DateField()),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Barril',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numBarril', models.PositiveIntegerField()),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.Ingreso')),
            ],
        ),
    ]
